# Site settings 配置站点
title: '廖柯宇的独立博客'
description: '昵称悟空，千禧一代，前端开发者/伪极客/灵魂摄影师，热爱技术&设计。很高兴能在这里与你分享我对技术和生活的思考。'
keyword: '廖柯宇, 廖柯宇的独立博客, 廖柯宇的博客, 前端, 前端开发, 前端博客, javascript, vuejs, nodejs, 设计'
logo: ''
url: 'http://liaokeyu.com' # your host
baseurl: '/'
theme-color: 'default' # theme color: pink or default

# Navigation links
nav:
  home: '/'
  tags: '/tags'

# Author 配置博主信息
author: '廖柯宇'
nickname: '悟空'
bio: '前端开发者，热爱技术&设计，简单乐观爱创造'
avatar: 'assets/img/profile.png'

# Build settings
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']
paginate: 6
paginate_path: 'page:num'

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagrame, juejin, github, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/lovecolcol'
  juejin: '//juejin.im/user/57a6f434165abd006159b4cc'
  instagram: '//www.instagram.com/steveliaocn'
  github: '//github.com/kaeyleo'

RSS: false

# tags
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Plugins
gems: [jekyll-paginate]
